version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    env_file: ./server/.env
    networks:
      - root_default
    restart: unless-stopped

  client:
    build:
      context: ./client
      args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "3000:3000"
    env_file: ./client/.env.local
    environment:
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    depends_on:
      - server
    networks:
      - root_default
    restart: unless-stopped

networks:
  root_default:
    external: true
